2024-10-02 09:27:41,569 (7f9b879890) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: f2c27da (Mon Sep 23 10:05:42 UTC 2024)
2024-10-02 09:27:41,570 (7f9b879890) :  DEBUG (core:361) - Using the elevated policy
2024-10-02 09:27:41,571 (7f9b879890) :  DEBUG (core:450) - Starting runtime component.
2024-10-02 09:27:41,577 (7f9b879890) :  DEBUG (core:450) - Starting caching component.
2024-10-02 09:27:41,579 (7f9b879890) :  DEBUG (core:450) - Starting data component.
2024-10-02 09:27:41,579 (7f9b879890) :  DEBUG (core:450) - Starting networking component.
2024-10-02 09:27:41,580 (7f9b879890) :  DEBUG (networking:266) - No cookie jar found
2024-10-02 09:27:41,583 (7f9b879890) :  DEBUG (networking:434) - Setting the default network timeout to 20.0
2024-10-02 09:27:41,587 (7f9b879890) :  DEBUG (core:450) - Starting localization component.
2024-10-02 09:27:41,588 (7f9b879890) :  INFO (localization:409) - Setting the default locale to en-us
2024-10-02 09:27:41,589 (7f9b879890) :  DEBUG (core:450) - Starting messaging component.
2024-10-02 09:27:41,591 (7f9b879890) :  DEBUG (core:450) - Starting debugging component.
2024-10-02 09:27:41,592 (7f9b879890) :  DEBUG (core:450) - Starting services component.
2024-10-02 09:27:41,593 (7f9b879890) :  DEBUG (core:450) - Starting myplex component.
2024-10-02 09:27:41,594 (7f9b879890) :  DEBUG (core:450) - Starting notifications component.
2024-10-02 09:27:41,595 (7f983f0b08) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.agents.thetvdb'
2024-10-02 09:27:42,470 (7f9b879890) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.agents.thetvdb in namespace 'metadata'
2024-10-02 09:27:42,505 (7f9b879890) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2024-10-02 09:27:42,529 (7f9b879890) :  ERROR (networking:197) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2024-10-02 09:27:42,537 (7f9b879890) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-f2c27da23/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-f2c27da23/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 243, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-f2c27da23/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 221, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-f2c27da23/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 159, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2024-10-02 09:27:42,587 (7f9b879890) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2024-10-02 09:27:42,587 (7f981c0b08) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2024-10-02 09:27:42,592 (7f9b879890) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2024-10-02 09:27:42,594 (7f981c0b08) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2024-10-02 09:27:42,595 (7f9817ab08) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400'
2024-10-02 09:27:42,602 (7f9b879890) :  DEBUG (core:150) - Finished starting framework core
2024-10-02 09:27:42,603 (7f9b879890) :  DEBUG (core:560) - Loading plug-in code
2024-10-02 09:27:43,192 (7f981c0b08) :  DEBUG (services:362) - Loaded services
2024-10-02 09:27:43,570 (7f9817ab08) :  DEBUG (core:538) - Machine identifier is fe9e79c742baa9f0ccb0dcfddce46939140831b1
2024-10-02 09:27:43,570 (7f9819db08) :  DEBUG (services:438) - No shared code to load
2024-10-02 09:27:43,571 (7f9817ab08) :  DEBUG (core:539) - Server version is 1.41.0.8994-f2c27da23
2024-10-02 09:27:45,335 (7f9b879890) :  DEBUG (core:566) - Finished loading plug-in code
2024-10-02 09:27:45,337 (7f9b879890) :  DEBUG (agentkit:1132) - Creating new agent class called TVDBAgent
2024-10-02 09:27:45,343 (7f9b879890) :  DEBUG (agentkit:937) - Updating agent information: [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'languages': ['en', 'fr', 'zh', 'sv', 'no', 'da', 'fi', 'nl', 'de', 'it', 'es', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'cs', 'ko', 'sl', 'hr'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'TheTVDB'}]
2024-10-02 09:27:45,347 (7f9b879890) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudG5zMTQKY29udHJpYnV0ZXNfdG9yNApzOQpsYW5ndWFnZXNiMXMyMApwZXJzaXN0X3N0b3JlZF9maWxlc2kwCnM3CnZlcnNpb25iMXMxNgpwcmltYXJ5X3Byb3ZpZGVyYjFzNQpwcmVmc3M3ClRoZVRWREJzNApuYW1lMQpzNwpUVl9TaG93MjMKczIKZW5zMgpmcnMyCnpoczIKc3ZzMgpub3MyCmRhczIKZmlzMgpubHMyCmRlczIKaXRzMgplc3MyCnBsczIKaHVzMgplbHMyCnRyczIKcnVzMgpoZXMyCmphczIKcHRzMgpjc3MyCmtvczIKc2xzMgpocnIwCg__'
2024-10-02 09:27:57,230 (7f9b879890) :  INFO (core:611) - Started plug-in
2024-10-02 09:27:57,231 (7f9b879890) :  DEBUG (socketinterface:160) - Starting socket server
2024-10-02 09:27:57,235 (7f9b879890) :  DEBUG (runtime:1117) - Created a thread named 'start'
2024-10-02 09:27:57,237 (7f9b879890) :  INFO (socketinterface:184) - Socket server started on port 36407
2024-10-02 09:27:57,239 (7f9b879890) :  INFO (pipeinterface:25) - Entering run loop
2024-10-02 09:27:57,240 (7f9b879890) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2024-10-02 09:27:57,255 (7f9b879890) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2024-10-02 09:27:57,260 (7f9b879890) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 151 bytes
2024-10-02 09:27:57,273 (7f976f7b08) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2024-10-02 09:27:57,279 (7f976d0b08) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2024-10-02 09:27:57,376 (7f976d0b08) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-f2c27da23/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2024-10-02 09:27:57,379 (7f976f7b08) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-f2c27da23/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2024-10-02 09:27:57,380 (7f976f7b08) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2024-10-02 09:27:57,378 (7f976d0b08) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2024-10-02 09:27:57,387 (7f976d0b08) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2024-10-02 09:27:57,388 (7f976f7b08) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2024-10-02 09:27:57,390 (7f976d0b08) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
2024-10-02 09:27:57,391 (7f976f7b08) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
